[versions]
kotlin = "2.4.10"
binaryCompat = "0.16.3"
sqldelight = "2.3.2"

[libraries]
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
binaryCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompat" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
